[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Range"
    Access-Control-Expose-Headers = "Content-Length, Content-Range, Accept-Ranges"
[[redirects]]
  from = "/api/*"
  to = "http://frp.freefrp.net:40404/:splat"
  status = 200